// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "v1"
#define AUTOTB_TVIN_v1  "../tv/cdatafile/c.hls_main.autotvin_v1.dat"
// wrapc file define: "v2"
#define AUTOTB_TVIN_v2  "../tv/cdatafile/c.hls_main.autotvin_v2.dat"
// wrapc file define: "v3"
#define AUTOTB_TVIN_v3  "../tv/cdatafile/c.hls_main.autotvin_v3.dat"
// wrapc file define: "ap_return"
#define AUTOTB_TVOUT_ap_return  "../tv/cdatafile/c.hls_main.autotvout_ap_return.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "ap_return"
#define AUTOTB_TVOUT_PC_ap_return  "../tv/rtldatafile/rtl.hls_main.autotvout_ap_return.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			v1_depth = 0;
			v2_depth = 0;
			v3_depth = 0;
			ap_return_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{v1 " << v1_depth << "}\n";
			total_list << "{v2 " << v2_depth << "}\n";
			total_list << "{v3 " << v3_depth << "}\n";
			total_list << "{ap_return " << ap_return_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int v1_depth;
		int v2_depth;
		int v3_depth;
		int ap_return_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern char hls_main (
char v1,
char v2,
char v3);

char AESL_WRAP_hls_main (
char v1,
char v2,
char v3)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		char AESL_return;

		// output port post check: "ap_return"
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data

			sc_bv<8> ap_return_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					ap_return_pc_buffer = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_ap_return))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: ap_return
				{
					// bitslice(7, 0)
					// {
						// celement: return(7, 0)
						// {
							sc_lv<8> return_lv0_0_1_0;
						// }
					// }

					// bitslice(7, 0)
					{
						// celement: return(7, 0)
						{
							// carray: (0) => (1) @ (0)
							{
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									return_lv0_0_1_0.range(7, 0) = sc_bv<8>(ap_return_pc_buffer.range(7, 0));
								}
							}
						}
					}

					// bitslice(7, 0)
					{
						// celement: return(7, 0)
						{
							// carray: (0) => (1) @ (0)
							{
								// sub                    : 
								// ori_name               : AESL_return
								// sub_1st_elem           : 
								// ori_name_1st_elem      : AESL_return
								// output_left_conversion : AESL_return
								// output_type_conversion : (return_lv0_0_1_0).to_uint64()
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									AESL_return = (return_lv0_0_1_0).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		AESL_transaction_pc++;

		return AESL_return;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "v1"
		char* tvin_v1 = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_v1);

		// "v2"
		char* tvin_v2 = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_v2);

		// "v3"
		char* tvin_v3 = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_v3);

		// "ap_return"
		char* tvout_ap_return = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_ap_return);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_v1, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_v1, tvin_v1);

		sc_bv<8> v1_tvin_wrapc_buffer;

		// RTL Name: v1
		{
			// bitslice(7, 0)
			{
				// celement: v1(7, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : v1
						// sub_1st_elem          : 
						// ori_name_1st_elem     : v1
						// regulate_c_name       : v1
						// input_type_conversion : v1
						if (&(v1) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> v1_tmp_mem;
							v1_tmp_mem = v1;
							v1_tvin_wrapc_buffer.range(7, 0) = v1_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_v1, "%s\n", (v1_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_v1, tvin_v1);
		}

		tcl_file.set_num(1, &tcl_file.v1_depth);
		sprintf(tvin_v1, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_v1, tvin_v1);

		// [[transaction]]
		sprintf(tvin_v2, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_v2, tvin_v2);

		sc_bv<8> v2_tvin_wrapc_buffer;

		// RTL Name: v2
		{
			// bitslice(7, 0)
			{
				// celement: v2(7, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : v2
						// sub_1st_elem          : 
						// ori_name_1st_elem     : v2
						// regulate_c_name       : v2
						// input_type_conversion : v2
						if (&(v2) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> v2_tmp_mem;
							v2_tmp_mem = v2;
							v2_tvin_wrapc_buffer.range(7, 0) = v2_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_v2, "%s\n", (v2_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_v2, tvin_v2);
		}

		tcl_file.set_num(1, &tcl_file.v2_depth);
		sprintf(tvin_v2, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_v2, tvin_v2);

		// [[transaction]]
		sprintf(tvin_v3, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_v3, tvin_v3);

		sc_bv<8> v3_tvin_wrapc_buffer;

		// RTL Name: v3
		{
			// bitslice(7, 0)
			{
				// celement: v3(7, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : v3
						// sub_1st_elem          : 
						// ori_name_1st_elem     : v3
						// regulate_c_name       : v3
						// input_type_conversion : v3
						if (&(v3) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> v3_tmp_mem;
							v3_tmp_mem = v3;
							v3_tvin_wrapc_buffer.range(7, 0) = v3_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_v3, "%s\n", (v3_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_v3, tvin_v3);
		}

		tcl_file.set_num(1, &tcl_file.v3_depth);
		sprintf(tvin_v3, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_v3, tvin_v3);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		char AESL_return = hls_main(v1, v2, v3);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_ap_return, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		sc_bv<8> ap_return_tvout_wrapc_buffer;

		// RTL Name: ap_return
		{
			// bitslice(7, 0)
			{
				// celement: return(7, 0)
				{
					// carray: (0) => (1) @ (0)
					{
						// sub                   : 
						// ori_name              : AESL_return
						// sub_1st_elem          : 
						// ori_name_1st_elem     : AESL_return
						// regulate_c_name       : return
						// input_type_conversion : AESL_return
						if (&(AESL_return) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> return_tmp_mem;
							return_tmp_mem = AESL_return;
							ap_return_tvout_wrapc_buffer.range(7, 0) = return_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_ap_return, "%s\n", (ap_return_tvout_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);
		}

		tcl_file.set_num(1, &tcl_file.ap_return_depth);
		sprintf(tvout_ap_return, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "v1"
		delete [] tvin_v1;
		// release memory allocation: "v2"
		delete [] tvin_v2;
		// release memory allocation: "v3"
		delete [] tvin_v3;
		// release memory allocation: "ap_return"
		delete [] tvout_ap_return;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);

		return AESL_return;
	}
}

